[project]
name = "ragwithazureopenai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lkidane", email = "lkidane@aimsammi.org" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.53.0",
    "requests>=2.34.2",
]

[project.scripts]
ragwithazureopenai = "ragwithazureopenai:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
